CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    phone_number VARCHAR(255),
    password VARCHAR(255),
    role SMALLINT
);

CREATE TABLE pet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname VARCHAR(255),
    description VARCHAR(255),
    registered_at DATE,
    adopted BOOLEAN,
    specie VARCHAR(255),
    size VARCHAR(255),
    sex VARCHAR(255),
    user_id INTEGER,
    CONSTRAINT fk_pet_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE pet_image_urls (
    pet_id BIGINT NOT NULL,
    image_urls VARCHAR(255),
    CONSTRAINT fk_pet_image_urls_pet FOREIGN KEY (pet_id) REFERENCES pet(id)
);

CREATE INDEX idx_pet_user_id ON pet(user_id);
CREATE INDEX idx_pet_adopted ON pet(adopted);
CREATE INDEX idx_pet_filters ON pet(specie, sex, size);
CREATE INDEX idx_pet_image_urls_pet_id ON pet_image_urls(pet_id);
